# 将User_FeatureVectors聚成40类

### 读取所有用户向量

In [2]:
import pandas as pd
import numpy as np
# Path of the file to read
User_filepath = "./user_feature_pca.csv"#可以选择
FeatureVectors = {}
Userfeatures_noid = []
User_id = []
data = pd.read_csv(User_filepath, header=0,sep=' ')
data_user = data.iloc[:,0]
print(data_user)
data_feature = data.iloc[:,1:]
data_feature
# with open(User_filepath, "r") as f:
#     # f.readline() # skip the header
#     for line in f:
#         line = line.split("\t")
#         vec = line[1].strip("[]").strip("\n").split(";") #[0] 是item id [1]是arm feature
#         FeatureVectors[int(line[0])] = np.array(vec).astype(float)
#         Userfeatures_noid.append(np.array(vec).astype(float))
#         User_id.append(int(line[0]))
# Userfeatures_noid = pd.DataFrame(Userfeatures_noid)
# Userfeatures_noid
       

0          0
1          1
2          2
3          3
4          4
        ... 
7171    7171
7172    7172
7173    7173
7174    7174
7175    7175
Name: user_id, Length: 7176, dtype: int64


,u0,u1,u2,u3,u4,u5,u6,u7,u8,u9,...,u15,u16,u17,u18,u19,u20,u21,u22,u23,u24
0,-1.674993,0.152371,-0.554478,0.847241,-0.487899,0.379005,0.038020,0.683137,-0.043919,0.463972,...,0.025993,-0.487937,-0.513339,-0.060585,0.092976,0.162210,-0.263889,-0.347352,0.251206,0.208874
1,0.353917,-1.110304,1.185043,0.134926,-0.119457,0.115978,-0.387008,0.258563,-0.518948,-0.095652,...,0.734863,0.624212,-0.383560,-0.332877,-0.399949,0.062644,-0.418552,0.275639,0.188519,0.255468
2,-0.333553,1.103801,0.204809,0.232690,0.007381,0.132940,0.401279,-1.488611,-0.436226,0.569142,...,0.290853,0.251065,-0.164117,-0.360368,-0.423455,0.713594,0.097480,-0.051655,0.547016,0.350105
3,-0.658980,1.172114,0.762873,-0.289276,0.313181,-0.195914,-0.190670,-1.212718,-0.201246,0.093425,...,-0.352097,0.541714,0.023365,-0.017354,0.213095,-0.118452,-0.016572,0.376097,-0.159158,-0.124515
4,-0.263066,-0.781668,-0.032065,-1.030237,-0.041411,-0.860592,-0.677270,-0.097401,-0.318732,0.046551,...,0.197960,-0.430306,0.372218,0.136370,0.498894,-0.193749,-0.210194,-0.270706,0.178125,-0.176187
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7171,0.404764,-0.846309,-0.645774,-0.188909,-0.138761,-0.583587,0.241269,-0.113076,-0.145269,0.295969,...,0.117326,-0.257680,-0.230332,0.268963,-0.653390,-0.647309,-0.405664,-0.040272,-0.325261,0.631514
7172,0.138108,-0.873551,0.685209,0.142144,-0.605445,1.214768,0.451691,-0.694564,-0.120286,-0.455424,...,0.429813,0.601006,-0.507452,-0.075559,-0.744555,0.350266,-0.340947,-0.065165,0.382320,0.235505
7173,1.334196,0.262405,-0.146614,-1.131377,0.207926,0.824497,-0.787195,-0.134796,-0.132404,0.463317,...,0.033094,0.299075,-0.276668,0.104060,-0.676064,0.904495,0.089272,-0.141311,0.509480,0.112142
7174,-0.423911,-0.368874,0.673537,0.627725,1.059992,-0.631193,-0.119376,0.054937,0.098089,-0.610454,...,0.313102,0.809837,0.353500,0.113543,-0.264847,0.908311,0.635354,0.354454,-0.537803,-0.327043


### 生成聚类向量

In [9]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
# 假设 user_vectors 是用户向量的集合，每个向量形状为 (n_features,)
Userfeatures_noid = data_feature
n_clusters = 40# 指定聚类的数量
kmeans = KMeans(n_clusters=n_clusters)
kmeans.fit(Userfeatures_noid)
centers = kmeans.cluster_centers_
for i in range(len(centers)):
    print("Class {}: {}".format(i+1, centers[i]))


# 计算轮廓系数
silhouette_avg = silhouette_score(Userfeatures_noid, kmeans.labels_)
print(f"轮廓系数：{silhouette_avg}")

Class 1: [ 0.26980467  0.70477468  0.23289483 -0.32200755  0.05255877  0.05830713
  0.80390654  0.22424225 -0.26453395  0.05505236 -0.14835931 -0.33798561
  0.15682744  0.47383648  0.11481233 -0.24745323 -0.25475637  0.01439714
  0.17790276  0.02869209 -0.09388317  0.14461081 -0.21132311  0.1789968
 -0.10626195]
Class 2: [-0.87355543 -0.33216121  0.33625185  0.49720494  0.40442158 -0.30393143
  0.33436943 -0.60832493 -0.08443697 -0.11935009 -0.08470055 -0.07702747
 -0.04926703 -0.06409124 -0.13478327  0.1292627   0.04319332 -0.16886024
 -0.18662851  0.13691916  0.07359246  0.15224965  0.15113492 -0.16750195
  0.06162921]
Class 3: [ 0.5229867  -0.6931007  -0.06182285  0.80889794  0.81661345 -0.00739741
 -0.59107942 -0.12074632 -0.0728757  -0.17664728 -0.03932805  0.25743818
  0.26535801  0.02280797  0.14708486  0.14803379  0.02758783  0.35462689
  0.28964916 -0.11169486  0.19674492  0.10937112 -0.04400464 -0.07311399
 -0.15049191]
Class 4: [-0.67884724 -0.37187739 -0.73229035 -0.3120279

### 生成用户聚类结果信息

In [10]:
silhouette_avg = silhouette_score(Userfeatures_noid, kmeans.labels_)
print(f"轮廓系数：{silhouette_avg}")
print("label",  kmeans.labels_)
print("num_label",  len(kmeans.labels_))
print(kmeans.labels_[1])

轮廓系数：0.06381194952702242
label [31 15 22 ... 21  1  2]
num_label 7176
15


### 同步存储聚类后的用户向量 和 映射关系

In [11]:
# 因为聚类了所以不用考虑原来用户id，类别顺序就是新的id
filename = "./{}clusters_FeatureVectors.dat".format(n_clusters)
with open(filename, 'w', newline='') as f:
    for i in range(centers.shape[0]):
        new_line = str(i) + '\t' + ';'.join(str(centers[i, :]).strip('[').strip(']').split()) + '\n'
        f.write(new_line)
print("done")

#label需要类别顺序与用户id对应，而不是与用户向量的index对应
label_dict = {}
for i in range(len(kmeans.labels_)):
    label_dict[str(data_user[i])] = int(kmeans.labels_[i])
import json
filename = "./{}clusters_labels.json".format(n_clusters)
with open(filename, 'w') as f:
    json.dump(label_dict, f)
print("done")


done
done


## 生成关系矩阵

### 读取聚类向量

In [12]:
import numpy as np
import pandas as pd

In [13]:
classfeatures = []
n_clusters=40
filename = "./{}clusters_FeatureVectors.dat".format(n_clusters)
with open(filename, "r") as f:
    # f.readline()# 跳过第一行
    for line in f:
        line = line.split("\t")
        vec = line[1].strip("[]").strip("\n").split(";") #[0] 是item id [1]是arm feature
        classfeatures.append(np.array(vec).astype(float))
classfeatures = pd.DataFrame(classfeatures)
classfeatures
       

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,0.269805,0.704775,0.232895,-0.322008,0.052559,0.058307,0.803907,0.224242,-0.264534,0.055052,...,-0.247453,-0.254756,0.014397,0.177903,0.028692,-0.093883,0.144611,-0.211323,0.178997,-0.106262
1,-0.873555,-0.332161,0.336252,0.497205,0.404422,-0.303931,0.334369,-0.608325,-0.084437,-0.119350,...,0.129263,0.043193,-0.168860,-0.186629,0.136919,0.073592,0.152250,0.151135,-0.167502,0.061629
2,0.522987,-0.693101,-0.061823,0.808898,0.816613,-0.007397,-0.591079,-0.120746,-0.072876,-0.176647,...,0.148034,0.027588,0.354627,0.289649,-0.111695,0.196745,0.109371,-0.044005,-0.073114,-0.150492
3,-0.678847,-0.371877,-0.732290,-0.312028,0.539467,-0.385635,0.131456,-0.515594,0.077810,0.086932,...,0.022506,0.114240,-0.230922,-0.141806,0.022071,0.057861,0.107603,-0.012563,-0.123092,0.033341
4,-0.228141,-0.728347,-0.141525,-0.848850,0.071067,-0.297201,-0.072332,-0.021744,0.213877,0.101981,...,-0.036892,0.016537,0.299942,0.027638,-0.023918,-0.059636,-0.127347,0.033298,-0.028230,-0.070346
5,1.250298,0.722827,-0.924838,0.854947,0.196956,-0.153652,-0.121788,-0.180631,-0.006756,-0.128495,...,0.019935,-0.228057,0.270797,-0.057447,-0.040507,0.081161,-0.096293,0.020019,0.179688,0.030882
6,0.912932,0.715488,0.448622,1.109491,0.555917,0.059597,-0.006235,-0.311059,0.056425,0.046016,...,0.142341,-0.043311,0.247961,0.013734,-0.001048,-0.174539,-0.094220,-0.043772,-0.027151,0.086802
7,-0.598220,1.282034,-0.548687,-0.295851,-0.003327,-0.227626,-0.311993,0.253916,0.119178,-0.077792,...,-0.055697,0.005350,-0.213373,-0.075995,0.070196,-0.040036,-0.008816,-0.028132,0.051116,0.019483
8,-0.990817,-0.318824,0.568384,-0.010470,-0.317868,0.411057,-0.222243,-0.683467,-0.122218,0.053897,...,-0.051614,-0.084090,0.253294,0.229276,-0.163443,0.007120,0.036159,0.026986,-0.030275,0.090049
9,1.197875,0.321874,0.295429,0.016123,-0.238731,0.402344,0.411645,0.381293,-0.385455,0.005137,...,-0.207591,-0.046180,-0.408568,0.205854,0.002550,0.051970,0.141620,-0.140685,0.252632,-0.185301


### 生成W

In [14]:
import numpy as np
import json
classfeatures = np.array(classfeatures)
n = len(classfeatures)
sparsityLevel = int(n/2)
W = np.zeros(shape=(n, n))

for i in range(n):
    sSim = 0
    for j in range(n):
        sim = np.dot(classfeatures[i], classfeatures[j])
        W[i][j] = sim
        sSim += sim
    W[i] /= sSim
SparseW = W

#小于阈值的置为0
if sparsityLevel > 0 and sparsityLevel < n:
    for i in range(n):
        similarity = sorted(W[i], reverse=False)
        threshold = similarity[sparsityLevel]
        for j in range(n):
            if W[i][j] <= threshold:
                SparseW[i][j] = 0
        SparseW[i] /= sum(SparseW[i])
# for i in range(len(SparseW)):
    
#     print(sum(SparseW[i]))

for i in range(n):
    # SparseW[i][i] = 0
    # if sum(SparseW[i]) != 0:
    #     SparseW[i][i] = np.linalg.norm(SparseW[i]) ** 2 / sum(SparseW[i])
    # else:
    SparseW[i][i] = 1
    SparseW[i] /= sum(SparseW[i])
print("SparseW --Opt", SparseW)

# for i in range(len(SparseW)):
    
#     print(sum(SparseW[i]))
#存储为json格式
# import json
filename = "./SparseW.json"
with open(filename, 'w') as f:
    json.dump(SparseW.T.tolist(), f)
print("save SparseW.json")
# W = np.load('./NYC/SparseW.npy')

SparseW --Opt [[0.54444415 0.         0.         ... 0.         0.03136945 0.01253992]
 [0.01566038 0.5        0.         ... 0.         0.01158294 0.04710812]
 [0.         0.00919118 0.55281636 ... 0.         0.         0.        ]
 ...
 [0.0239095  0.         0.0125164  ... 0.5        0.01186966 0.03030717]
 [0.         0.01375447 0.04082607 ... 0.01611961 0.5        0.        ]
 [0.00723051 0.         0.         ... 0.         0.         0.53845123]]
save SparseW.json
